### ISSUE TITLE
 can you get the jar? pls

### ISSUE THREAD

**Issue by Gtafgu** [Guillaume351/BuildBattles_Nukkit#1]
and thank you for getting the skywars plugin

**Comment by Guillaume351** [comment]
Hello,
Sorry I didn't see your issue
You can create a jar using maven, or I will do one in a few days & upload it

**Comment by Guillaume351** [comment]
Here is the .jar for the current version : https://easyupload.io/pwe218
The game map has to be named "game", and the waiting map is the default map of the server
